# Generated by Django 5.0.6 on 2024-05-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhythm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='movie',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
