# Generated by Django 5.0.6 on 2024-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhythm', '0004_alter_song_image_alter_song_song_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('music', models.CharField(max_length=100000000)),
            ],
        ),
    ]
