# Generated by Django 5.0.6 on 2024-07-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhythm', '0006_alter_song_image_alter_song_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='Tags',
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
